name: Scala CI

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches: [pull-request-using-gh-actions]

      # assigned,unassigned,labeled,unlabeled,opened,edited,closed,reopened,synchronize,ready_for_review,locked,unlocked,review_requested,review_request_removed
      # you add/remove multiple labels at the same time, the event of each label will trigger its own workflow run.
jobs:
  job1:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: sbt test

      - name: run echo
        run: echo "pr-event-merge-1"
#  job2:
#    name: ping-pong
#    runs-on: ubuntu-latest
#    steps:
#      - name: Event Information
#        run: |
#           echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
#      - name: PONG - Dispatch response to received PING
#        if: github.event.action == 'ping'
#        run: |
#          curl -X POST https://api.github.com/repos/sakshigawande12/spring-unit-testing-with-junit-and-mockito-master/dispatches \
#           -H 'Accept: application/vnd.github.everest-preview+json' \
#          -u ${{ secrets.ACCESS_TOKEN }} \
#           --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
